In [38]:
# numpy import
import numpy as np

In [39]:
# word embedding:  dictionary that maps word indexes to weights (numbers)
embedding = {i: np.random.normal(0, .1, 10) for i in range(10001)}

In [40]:
# observe what it is
embedding

{0: array([ 0.06323832, -0.10035696, -0.05223972,  0.08336624,  0.00977041,
        -0.09007563, -0.11180536,  0.11039989,  0.09717328,  0.23413428]),
 1: array([-0.06484713,  0.09198398, -0.0948057 ,  0.02882846,  0.13828319,
         0.00695141,  0.09497052,  0.07193349, -0.04219346, -0.00684858]),
 2: array([-0.08648084, -0.23495914,  0.10694521,  0.09112686, -0.19735691,
         0.1427312 , -0.03776733,  0.05426986,  0.08482248, -0.01624501]),
 3: array([ 0.02723016,  0.08356108,  0.01484488, -0.04706645,  0.17128542,
        -0.11948915,  0.04122046, -0.01040174, -0.00856813,  0.0507977 ]),
 4: array([-0.05596847,  0.03471625,  0.05695519,  0.10038591,  0.01852836,
        -0.01628661, -0.05931702, -0.21640299, -0.01443685,  0.02696678]),
 5: array([ 0.2139903 , -0.01451278, -0.02392046,  0.02441634,  0.02499676,
         0.06933082, -0.12193901,  0.17832837, -0.0528972 ,  0.01055566]),
 6: array([-0.07097674, -0.04504361, -0.16848062,  0.1494648 ,  0.10919946,
         0.1268513

In [41]:
# sample data sequences
sequence1 = [1, 13, 24, 12, 55, 1, 2, 3]
sequence2 = [2, 24, 15, 23, 3, 2, 1, 5]

In [42]:
# sample data point to hold our data
dat_point1 = np.zeros((8, 10))

In [43]:
# empty zeroes
dat_point1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
# fill each row with the weight for each corresponding word
for idx, val in enumerate(sequence1):
    dat_point1[idx] = embedding[val]

In [45]:
# this is the result that we get
dat_point1

array([[-0.06484713,  0.09198398, -0.0948057 ,  0.02882846,  0.13828319,
         0.00695141,  0.09497052,  0.07193349, -0.04219346, -0.00684858],
       [-0.08275171,  0.16205195, -0.16576568,  0.11029038, -0.05632854,
         0.04405334, -0.18159039,  0.02444324,  0.09423488,  0.18303543],
       [ 0.12059998, -0.00507855, -0.02514121, -0.03391668, -0.17587239,
         0.04950735, -0.06962518,  0.02580986,  0.02334189,  0.07492216],
       [ 0.07111222,  0.11346216,  0.14912683,  0.03422942,  0.07815692,
         0.01847597,  0.11173525, -0.20918223, -0.06216536, -0.06246555],
       [ 0.09041323, -0.1391823 , -0.19542774,  0.13298726,  0.15544435,
        -0.01688918,  0.01826828, -0.24960157, -0.13929985, -0.1262616 ],
       [-0.06484713,  0.09198398, -0.0948057 ,  0.02882846,  0.13828319,
         0.00695141,  0.09497052,  0.07193349, -0.04219346, -0.00684858],
       [-0.08648084, -0.23495914,  0.10694521,  0.09112686, -0.19735691,
         0.1427312 , -0.03776733,  0.05426986

In [46]:
# notice how the word indices match the embedding weights
embedding[1]

array([-0.06484713,  0.09198398, -0.0948057 ,  0.02882846,  0.13828319,
        0.00695141,  0.09497052,  0.07193349, -0.04219346, -0.00684858])

In [47]:
# function to 
def create_word_matrix(sequence, embedding, embedding_dim=10):
    data_point = np.zeros((len(sequence), embedding_dim))
    for idx, val in enumerate(sequence):
        data_point[idx] = embedding[val]
        
    return data_point

In [48]:
create_word_matrix(sequence1, embedding, 10)

array([[-0.06484713,  0.09198398, -0.0948057 ,  0.02882846,  0.13828319,
         0.00695141,  0.09497052,  0.07193349, -0.04219346, -0.00684858],
       [-0.08275171,  0.16205195, -0.16576568,  0.11029038, -0.05632854,
         0.04405334, -0.18159039,  0.02444324,  0.09423488,  0.18303543],
       [ 0.12059998, -0.00507855, -0.02514121, -0.03391668, -0.17587239,
         0.04950735, -0.06962518,  0.02580986,  0.02334189,  0.07492216],
       [ 0.07111222,  0.11346216,  0.14912683,  0.03422942,  0.07815692,
         0.01847597,  0.11173525, -0.20918223, -0.06216536, -0.06246555],
       [ 0.09041323, -0.1391823 , -0.19542774,  0.13298726,  0.15544435,
        -0.01688918,  0.01826828, -0.24960157, -0.13929985, -0.1262616 ],
       [-0.06484713,  0.09198398, -0.0948057 ,  0.02882846,  0.13828319,
         0.00695141,  0.09497052,  0.07193349, -0.04219346, -0.00684858],
       [-0.08648084, -0.23495914,  0.10694521,  0.09112686, -0.19735691,
         0.1427312 , -0.03776733,  0.05426986

In [49]:
# wrap up our sequences in a list
sequences = [sequence1, sequence2]

In [50]:
# final matrix to hold our embedding data
word_data = np.zeros((2, 8, 10))

In [51]:
# fill in each row of the dataset with the encoded embedding data
for idx, row in enumerate(word_data):
    word_data[idx] = create_word_matrix(sequences[idx], embedding)

In [52]:
# this is what a single data point would look like
word_data[0]

array([[-0.06484713,  0.09198398, -0.0948057 ,  0.02882846,  0.13828319,
         0.00695141,  0.09497052,  0.07193349, -0.04219346, -0.00684858],
       [-0.08275171,  0.16205195, -0.16576568,  0.11029038, -0.05632854,
         0.04405334, -0.18159039,  0.02444324,  0.09423488,  0.18303543],
       [ 0.12059998, -0.00507855, -0.02514121, -0.03391668, -0.17587239,
         0.04950735, -0.06962518,  0.02580986,  0.02334189,  0.07492216],
       [ 0.07111222,  0.11346216,  0.14912683,  0.03422942,  0.07815692,
         0.01847597,  0.11173525, -0.20918223, -0.06216536, -0.06246555],
       [ 0.09041323, -0.1391823 , -0.19542774,  0.13298726,  0.15544435,
        -0.01688918,  0.01826828, -0.24960157, -0.13929985, -0.1262616 ],
       [-0.06484713,  0.09198398, -0.0948057 ,  0.02882846,  0.13828319,
         0.00695141,  0.09497052,  0.07193349, -0.04219346, -0.00684858],
       [-0.08648084, -0.23495914,  0.10694521,  0.09112686, -0.19735691,
         0.1427312 , -0.03776733,  0.05426986

In [53]:
# dimensions for a single sample!
word_data[0].shape

(8, 10)

In [54]:
# dimensions for our entire dataset!
word_data.shape

(2, 8, 10)

In [55]:
# we'll now 'flatten' our dataset to get it ready for matrix multiplications
word_data = word_data.reshape(2, -1)

# and our new shape
word_data.shape

(2, 80)

In [56]:
# the dense layer for matrix multiplications
dense_layer = np.random.normal(0, .01, size=(80, 64))

In [57]:
# a numpy array of weights
dense_layer

array([[ 0.00743981,  0.00924056, -0.00883331, ...,  0.00708312,
        -0.00696877,  0.0013606 ],
       [-0.0119072 ,  0.00028781, -0.00069322, ...,  0.00299221,
        -0.00530507, -0.0095144 ],
       [-0.00986232,  0.02123542, -0.01092656, ..., -0.01074764,
         0.00147388, -0.00979551],
       ...,
       [ 0.01194761,  0.01911312, -0.01024173, ...,  0.00531607,
        -0.00941358, -0.00079337],
       [-0.00446759,  0.00059996, -0.01112229, ..., -0.0078625 ,
        -0.00584295, -0.01194268],
       [-0.00806239,  0.00439268,  0.00982837, ..., -0.00770262,
        -0.01763201, -0.01461667]])

In [58]:
# the relu activation to clip negative values to 0
def relu(X):
    return np.maximum(0, X)

In [59]:
X_hidden1 = word_data @ dense_layer
# the value of X_hidden1
X_hidden1

array([[-9.13658805e-03,  5.63531204e-03,  9.79482151e-03,
         3.66372192e-03,  1.66840491e-02,  1.10017188e-02,
        -2.10854538e-03, -4.62866793e-03, -4.39922520e-03,
        -5.90187128e-03, -1.40241026e-02,  8.13395568e-03,
        -1.49749206e-02, -1.31356541e-02,  3.29016877e-03,
         9.65693370e-04, -4.73223194e-03,  8.17748287e-04,
         1.62976595e-02,  9.93927323e-03, -4.97476134e-03,
         3.81332591e-03, -1.15404558e-02, -1.88735172e-03,
        -3.66795477e-03, -5.24819237e-03, -4.51779401e-04,
         6.15868420e-03, -8.41681092e-03,  1.07626369e-02,
        -8.15539777e-03,  8.16725512e-03, -2.16628287e-02,
        -4.82301273e-03,  5.92589355e-03, -7.22992037e-04,
        -1.52915834e-03,  1.17852540e-02, -1.91857426e-03,
        -3.08699754e-03,  3.28970152e-03, -8.36020470e-04,
         6.49512981e-03,  6.01191166e-06,  1.46711207e-03,
         1.34307546e-02, -1.07264424e-02, -8.24046816e-03,
        -3.77482410e-02, -1.03205945e-02, -2.61315236e-0

In [ ]:
# pass it through ReLU to transform
X_hidden1 = relu(X_hidden1)

In [60]:
# do it one more time for a second dense layer
dense_layer2 = np.random.normal(0, .01, size=(64, 64))

In [61]:
# one more matrix multiplication for the second dense layer
X_hidden2 = X_hidden1 @ dense_layer2
# and pass it through relu activation
X_hidden2 = relu(X_hidden2)

In [62]:
# we'll now create our sigmoid activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# and the final layer
dense_layer3 = np.random.normal(0, .01, size = (64, 1))

# and our prediction
y_hat = X_hidden2 @ dense_layer3
# and apply the activation
y_hat = sigmoid(y_hat)

In [63]:
# and our initial set of predictions
y_hat

array([[0.49998435],
       [0.49999583]])

If we wanted to put the entire process into one code block, we could do it like the following:

In [78]:
# this will create the forward pass to push our data through the neural network
y = np.array([[1, 0]])

# will do this for 5 epochs (training rounds)
for i in range(5):
    word_data = np.zeros((2, 8, 10))
    # load data into the word embedding
    for idx, row in enumerate(word_data):
        word_data[idx] = create_word_matrix(sequences[idx], embedding)
    # reshape it so it's two dimensional (the flatten layer)
    word_data = word_data.reshape(2, -1)
    # matrix multiply
    X_hidden1 = word_data @ dense_layer
    # relu activation
    X_hidden1 = relu(X_hidden1)
    # do it one more time
    X_hidden2 = X_hidden1 @ dense_layer2
    X_hidden2 = relu(X_hidden2)
    # and now create the output layer
    out = X_hidden2 @ dense_layer3
    # sigmoid to get the final probabilities
    y_hat = sigmoid(out)
    # you would calculate the final error at each round and use that to update the weights (the backward pass)
    gradient = y - y_hat

### Dealing With Sequential Dependency

So far, we've looked at two different layers:  the word embedding, which maps weights to individual words, and dense layers, which are just straight matrix multiplications.  

However, a unique aspect of neural networks is that you can use a variety of different neural network layers, and they allow you to connect one part of your data to the next in a different way, that can help you capture particular patterns in your data.  

Since we are dealing with natural language, an important level of detail we want to pay attention to is the **order in which words appear**.  Natural language is built to use words around it to convey meaning, but these details are not captured as well as they could be with our current setup.  

The next, more specialized layer that we're going to look at is something called a **recurrent neural network layer**.  It's frequently used for time series and natural language data because its calculation technique naturally captures sequential detail.  

Here's how it works:

In [103]:
# the forward pass for a recurrent neural network
timesteps = 8 # number of samples in our sequence
input_features = 10 # number of columns of weights for each sample
output_features = 32 # number of columns each sample will have at the end

# create a bunch of weights for multiplications -- because that's what Neural Networks do
W = np.random.random((output_features, input_features))
U = np.random.random((output_features, output_features))
b = np.random.random((output_features, ))

# material we are going to use to store data after computing the 
# entire layer for every sample
layer_outputs = []

# recreate our word embedding
word_data = np.random.random((2, 8, 10))

for sample in word_data:
    state_t = np.zeros((output_features, ))
    # will contain sequential data after each step / sample
    sample_outputs = []
    for word in sample:
        # for each word, do these matrix operations
        output_t = np.tanh(W @ word) + U @ state_t + b
        # append the end
        sample_outputs.append(output_t)
        # set the new state previous to the last state
        state_t = output_t
    layer_outputs.append(sample_outputs)

In an actual neural network, it would look like this:

In [ ]:
# sequential model with RNN built into it
mod = keras.models.Sequential([
      keras.layers.Embedding(10000, 64, input_length = 300),
      # notice we don't flatten -- sequential layers typically take 3 layers in -- 2 layers out
      keras.layers.SimpleRNN(32),
      keras.layers.Dense(64, activation = 'relu'),
      keras.layers.Dense(64, activation = 'relu'),
      keras.layers.Dense(1, activation = 'sigmoid')
])

### Your Turn:  

Try and re-run your Neural network, but with two different layers:

 - `SimpleRnn`:  What we just created
 - `LSTM`:  This is a slightly more advanced version of an RNN that 'forgets' certain columns that have a low signal