In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor, plot_tree
import numpy as np

In [4]:
df   = pd.read_csv(r"/Users/lauverm/dat-11-15/Homework/Unit2/data/housing.csv")
tree = DecisionTreeRegressor(max_depth = 4)

In [5]:
X = df.drop('PRICE', axis = 1)
y = df['PRICE']

tree.fit(X, y)

DecisionTreeRegressor(criterion='mse', max_depth=4, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [6]:
import matplotlib.pyplot as plt

plt.figure(figsize = (18, 12))

plot_tree(tree, fontsize = 12, feature_names = X.columns, filled = True);

In [8]:
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [9]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: PRICE, Length: 506, dtype: float64

In [10]:
# step 1:  start off with a naive prediction for your dataset
guess = y.mean()

In [11]:
guess

22.532806324110698

In [12]:
gradient = y - guess

In [13]:
tree

DecisionTreeRegressor(criterion='mse', max_depth=4, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [14]:
tree.fit(X, gradient)

DecisionTreeRegressor(criterion='mse', max_depth=4, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [15]:
tree.predict(X)

array([  4.8944664 ,  -0.90306273,  10.21597416,  10.21597416,
        10.21597416,  -0.90306273,  -0.90306273,  -2.51197299,
        -2.51197299,  -2.51197299,  -2.51197299,  -0.90306273,
        -2.51197299,  -0.90306273,  -0.90306273,  -0.90306273,
        -0.90306273,  -6.29384529,  -0.90306273,  -0.90306273,
        -6.29384529,  -0.90306273,  -6.29384529,  -6.29384529,
        -6.29384529,  -6.29384529,  -6.29384529,  -6.29384529,
        -0.90306273,   4.8944664 ,  -6.29384529,  -0.90306273,
        -6.29384529,  -6.29384529,  -6.29384529,  -0.90306273,
        -0.90306273,  -0.90306273,  -0.90306273,   4.8944664 ,
        10.21597416,   4.8944664 ,  -0.90306273,  -0.90306273,
        -0.90306273,  -0.90306273,  -0.90306273,  -2.51197299,
        -2.51197299,  -2.51197299,  -0.90306273,  -0.90306273,
        -0.90306273,  -0.90306273,  -2.51197299,  10.21597416,
        -0.90306273,   4.8944664 ,  -0.90306273,  -0.90306273,
        -0.90306273,  -2.51197299,  -0.90306273,   4.89

In [16]:
guess += tree.predict(X)

In [17]:
guess

array([27.42727273, 21.62974359, 32.74878049, 32.74878049, 32.74878049,
       21.62974359, 21.62974359, 20.02083333, 20.02083333, 20.02083333,
       20.02083333, 21.62974359, 20.02083333, 21.62974359, 21.62974359,
       21.62974359, 21.62974359, 16.23896104, 21.62974359, 21.62974359,
       16.23896104, 21.62974359, 16.23896104, 16.23896104, 16.23896104,
       16.23896104, 16.23896104, 16.23896104, 21.62974359, 27.42727273,
       16.23896104, 21.62974359, 16.23896104, 16.23896104, 16.23896104,
       21.62974359, 21.62974359, 21.62974359, 21.62974359, 27.42727273,
       32.74878049, 27.42727273, 21.62974359, 21.62974359, 21.62974359,
       21.62974359, 21.62974359, 20.02083333, 20.02083333, 20.02083333,
       21.62974359, 21.62974359, 21.62974359, 21.62974359, 20.02083333,
       32.74878049, 21.62974359, 27.42727273, 21.62974359, 21.62974359,
       21.62974359, 20.02083333, 21.62974359, 27.42727273, 32.74878049,
       21.62974359, 21.62974359, 21.62974359, 21.62974359, 21.62

In [18]:
y - guess

0     -3.427273
1     -0.029744
2      1.951220
3      0.651220
4      3.451220
         ...   
501   -5.027273
502   -1.029744
503   -8.848780
504   -5.427273
505   -9.729744
Name: PRICE, Length: 506, dtype: float64

In [19]:
gradient = y - guess

In [20]:
tree.fit(X, gradient)

DecisionTreeRegressor(criterion='mse', max_depth=4, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [21]:
guess += tree.predict(X)

In [22]:
guess

array([26.63939202, 20.84186289, 31.96089979, 34.19185936, 34.19185936,
       25.51446953, 20.84186289, 20.56864878, 18.08926959, 20.56864878,
       20.56864878, 20.84186289, 20.56864878, 20.84186289, 20.84186289,
       20.84186289, 25.47427859, 16.78677649, 20.84186289, 20.84186289,
       16.78677649, 20.84186289, 16.78677649, 16.78677649, 16.78677649,
       16.78677649, 16.78677649, 16.78677649, 20.84186289, 26.63939202,
       16.78677649, 20.84186289, 14.3073973 , 16.78677649, 16.78677649,
       20.84186289, 20.84186289, 20.84186289, 25.47427859, 29.16366301,
       34.48517077, 29.16366301, 23.36613388, 23.36613388, 20.84186289,
       20.84186289, 20.84186289, 20.56864878, 18.08926959, 20.56864878,
       20.84186289, 20.84186289, 22.78530331, 22.78530331, 20.56864878,
       33.90434021, 20.84186289, 26.63939202, 20.64434595, 20.84186289,
       20.84186289, 19.23295263, 20.84186289, 26.63939202, 34.19185936,
       22.78530331, 22.78530331, 22.78530331, 20.84186289, 22.78

In [23]:
gradient = y - guess

In [24]:
tree.fit(X, gradient)

DecisionTreeRegressor(criterion='mse', max_depth=4, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [25]:
guess += tree.predict(X)

In [26]:
guess[:5]

array([26.59189641, 22.15935565, 31.91340417, 34.14436374, 34.14436374])

In [27]:
y[:5]

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: PRICE, dtype: float64

In [28]:
learning_rate = 0.1

In [29]:
gradient = y - guess

In [30]:
tree.fit(X, gradient)

DecisionTreeRegressor(criterion='mse', max_depth=4, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [31]:
guess += tree.predict(X)*learning_rate

In [32]:
from sklearn.ensemble import GradientBoostingRegressor

In [33]:
gbm = GradientBoostingRegressor()

In [34]:
gbm.get_params()

{'alpha': 0.9,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'ls',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'presort': 'auto',
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [35]:
import xgboost as xgb

In [36]:
mod = xgb.XGBRegressor()

In [39]:
mod.get_params()

{'base_score': 0.5,
 'booster': 'gbtree',
 'colsample_bylevel': 1,
 'colsample_bytree': 1,
 'gamma': 0,
 'learning_rate': 0.1,
 'max_delta_step': 0,
 'max_depth': 3,
 'min_child_weight': 1,
 'missing': None,
 'n_estimators': 100,
 'n_jobs': 1,
 'nthread': None,
 'objective': 'reg:linear',
 'random_state': 0,
 'reg_alpha': 0,
 'reg_lambda': 1,
 'scale_pos_weight': 1,
 'seed': None,
 'silent': True,
 'subsample': 1}

In [42]:
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(X, y, random_state = 24, test_size = 0.2)

In [43]:
mod.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=True, subsample=1)